### ISSUE TITLE
scripts should be searchable

### ISSUE THREAD

**Issue by clararaubertas** [Parallactic/calling-congress#26]
quick & dirty full-text search to start

**Comment by clararaubertas** [comment]
possibly through https://devcenter.heroku.com/articles/bonsai

**Comment by clararaubertas** [comment]
https://devcenter.heroku.com/articles/full-text-search

**Comment by faraocious** [comment]
hmm, good point! Postgres could definitely be a good compromise between ES and MySQL

**Comment by clararaubertas** [comment]
https://medium.com/@leighsn/simple-pg-search-example-postgresql-for-your-heroku-rails-app may be the best way to at least get initial functionality going
